// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUduJmeXRw0JtP2nVZ3MHffDm9PYTFvpQ',
    appId: '1:691608122869:web:df7e328e1e9bce55289cbc',
    messagingSenderId: '691608122869',
    projectId: 'seminar-prediction-app',
    authDomain: 'seminar-prediction-app.firebaseapp.com',
    storageBucket: 'seminar-prediction-app.appspot.com',
    measurementId: 'G-2RPJR35GJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpZQKwdHr_82apepvHoW2TYETRQuNNjGY',
    appId: '1:691608122869:android:2701d46de1829f08289cbc',
    messagingSenderId: '691608122869',
    projectId: 'seminar-prediction-app',
    storageBucket: 'seminar-prediction-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGSzWioM-YC8lPJ80-pHctqXp1cEFBI7I',
    appId: '1:691608122869:ios:cded0ab229770e96289cbc',
    messagingSenderId: '691608122869',
    projectId: 'seminar-prediction-app',
    storageBucket: 'seminar-prediction-app.appspot.com',
    iosBundleId: 'com.example.initialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGSzWioM-YC8lPJ80-pHctqXp1cEFBI7I',
    appId: '1:691608122869:ios:cded0ab229770e96289cbc',
    messagingSenderId: '691608122869',
    projectId: 'seminar-prediction-app',
    storageBucket: 'seminar-prediction-app.appspot.com',
    iosBundleId: 'com.example.initialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUduJmeXRw0JtP2nVZ3MHffDm9PYTFvpQ',
    appId: '1:691608122869:web:96b8fcbe18f86b35289cbc',
    messagingSenderId: '691608122869',
    projectId: 'seminar-prediction-app',
    authDomain: 'seminar-prediction-app.firebaseapp.com',
    storageBucket: 'seminar-prediction-app.appspot.com',
    measurementId: 'G-YBXG2D2FYC',
  );
}
